 - name: metallb installation 
   get_url:
     url: "{{ MetaLB_URL }}"
     dest: "/k8s-multinodes-yamls/metallb-native.yml"

 - shell:
     cmd: "{{ item }}"
   environment:
     - KUBECONFIG: /etc/kubernetes/admin.conf
   async: 3600
   poll: 10
   loop:
     - kubectl apply -f /k8s-multinodes-yamls/metallb-native.yml
     - kubectl wait --for=condition=Ready pod --all=true --namespace metallb-system --timeout 60m
     - kubectl apply -f /k8s-multinodes-yamls/MetaLB-IP-Pool.yml

 - block:  
      - name: download cni repos
        ansible.builtin.git:
          depth: 1
          repo: "{{ item.repo }}"
          dest: "{{ item.dest }}"
        loop:
          - { repo: "{{ Multus_URL }}" , dest: /tmp/multus-cni }
          - { repo: "{{ Whereabouts_URL }}", dest: /tmp/Whereabouts }
     
      - name: install whereabouts 
        shell:
          cmd: "{{ item }}"
        environment:
          - KUBECONFIG: /etc/kubernetes/admin.conf
        async: 3600
        poll: 10
        loop:
          - kubectl apply -f /tmp/Whereabouts/doc/crds/daemonset-install.yaml 
          - kubectl apply -f /tmp/Whereabouts/doc/crds/whereabouts.cni.cncf.io_ippools.yaml 
          - kubectl apply -f /tmp/Whereabouts/doc/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
          - kubectl wait --for=condition=Ready pod --all=true --namespace kube-system --timeout 60m

      - name: install multus
        shell:
          cmd: "{{ item }}"
        environment:
          - KUBECONFIG: /etc/kubernetes/admin.conf
        async: 3600
        poll: 10
        loop:
          - kubectl apply -f /tmp/multus-cni/deployments/multus-daemonset.yml
          - kubectl wait --for=condition=Ready pod --all=true --namespace kube-system --timeout 60m  
          - kubectl apply -f /k8s-multinodes-yamls/multus.yml  
   
   when: set_network_storage
