#################################################################################
#Importnatant_Notes:                                                            #
#            - Don't change the names of groups in the ansible inventory file.  #
#            - leave hosts: all (don't change)                                  #
#################################################################################

   - hosts: all      
     roles:
       - etc-hosts       
       - prepare-nodes 
       - k8s-preinstall   
       - longhorn 
     vars_files:
       - vars.yml   
     tasks:
       - name: cluster_initialzation 
         ansible.builtin.include_tasks: "../include.d/cluster_initialize.yml"
         when: inventory_hostname in groups['control_nodes']

       - name: join nodes
         ansible.builtin.include_tasks: "../include.d/join_workers.yml"

       - name: Cluster playbooks
         block:
           - name: Control plane resources 
             ansible.builtin.include_tasks: "../include.d/controllers_resources.yml"

           - name: cni plugins
             ansible.builtin.include_tasks: "../include.d/cni_plugins.yml"
    
           - name: install ingress
             ansible.builtin.include_tasks: "../include.d/ingress.yml"
    
           - name: install longhorn
             ansible.builtin.include_tasks: "../include.d/longhorn.yml"
    
           - name: finalize installation 
             ansible.builtin.include_tasks: "../include.d/finalize.yml"

         when: inventory_hostname in groups['control_nodes']
        
       - name: docker authtoken
         ansible.builtin.include_tasks: "../include.d/docker_authtoken.yml"
